dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-log-dev 
script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - cmake CMakeLists.txt && make
